Mhasb.Wsit.Web.Admin/Controllers/IndustryController.cs
using Mhasb.Domain.Commons;
using Mhasb.Services.Commons;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;


namespace Mhasb.Wsit.Web.Areas.Commons.Controllers
{
    public class IndustryController : Controller
    {
        private IIndustryService iService = new IndustryService();

        //
        // GET: /Commons/Industry/
        public ActionResult Index()
        {
            //var model = iService.GetAllIndustries();
            //return View(model);
          return View("Index1");
        }

        public ActionResult List(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<Industry> Industry = iService.GetAllIndustries();
            if (!String.IsNullOrEmpty(searchString))
            {
                Industry = Industry.Where(s => s.IndustryName.Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return PartialView(Industry.ToPagedList(pageNumber, pageSize));

        }


        //
        // GET: /Commons/Industry/Details/5
        public ActionResult Details(int id)
        {
            var model = iService.GetSingleIndustry(id);
            return View(model);
        }

        //
        // GET: /Commons/Industry/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Commons/Industry/Create
        [HttpPost]
        public ActionResult Create(Industry industry)
        {
            try
            {
                iService.CreateIndustry(industry);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Commons/Industry/Edit/5
        public ActionResult Edit(int id)
        {
            var model = iService.GetSingleIndustry(id);
            return View(model);
        }

        //
        // POST: /Commons/Industry/Edit/5
        [HttpPost]
        public ActionResult Edit(Industry industry)
        {
            try
            {
                iService.UpdateIndustry(industry);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        public String DeleteConfirmed(int id)
        {
            try
            {
                iService.DeleteIndustry(id);
                return "Success";
                // return RedirectToAction("Index");
            }
            catch
            {
                return "Failed";
            }
        }
    }
}

Mhasb.Wsit.Web.Admin/Views/Industry/Create.cshtml
@model Mhasb.Domain.Commons.Industry
<div class="row">
    <div class="col-sm-12">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="fa fa-edit"></i>Country
                </h3>
            </div>
            <div class="box-content">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true)



                        <div class="form-group">
                            <label for="textfield" class="control-label col-sm-2">@Html.LabelFor(model => model.IndustryName)</label>
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.IndustryName, new { type = "text", name = "textfield", id = "textfield", @class = "form-control" })

                                <span class="help-block">@Html.ValidationMessageFor(model => model.IndustryName)</span>
                            </div>
                        </div>
                       
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Create</button>
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn" })
                        </div>
                    </div>

                }


            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")

Mhasb.Wsit.Web.Admin/Views/Industry/Details.cshtml
@model Mhasb.Domain.Commons.Industry


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Industry</h4>
    	<hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IndustryName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IndustryName)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Mhasb.Wsit.Web.Admin/Views/Industry/Edit.cshtml
@model Mhasb.Domain.Commons.Industry
<div class="row">
    <div class="col-sm-12">
        <div class="box">
            <div class="box-title">
                <h3>
                    <i class="fa fa-edit"></i>Country
                </h3>
            </div>
            <div class="box-content">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true)



                        <div class="form-group">
                            <label for="textfield" class="control-label col-sm-2">@Html.LabelFor(model => model.IndustryName)</label>
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.IndustryName, new { type = "text", name = "textfield", id = "textfield", @class = "form-control" })

                                <span class="help-block">@Html.ValidationMessageFor(model => model.IndustryName)</span>
                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Save Changes</button>
                            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn" })
                        </div>
                    </div>

                }


            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")

Mhasb.Wsit.Web.Admin/Views/Industry/Index.cshtml
@model IEnumerable<Mhasb.Domain.Commons.Industry>



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p class="btn btn-success link">
        @Html.ActionLink("Create New", "Create", new { area = "commons" }, new { @class = "link" })
    </p>
    <div id="alert"></div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IndustryName)
            </th>
            <th></th>
        </tr>

        @if (!Model.Any())
        {
            <tr><td class="alert-success" colspan="4">There are no Industry</td></tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IndustryName)
                    </td>
                    <td>
                        <div class="btn btn-success link">
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "link" })
                        </div>
                        <div class="btn btn-info link">
                            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "link" })
                        </div>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#pop-up-@item.Id">
                            Delete
                        </button>
                        @*<a href="javascript:void(0)"  class="btn btn-primary" data-toggle="modal" data-target="#pop-up-1" data-id="@item.Id">Delete</a>*@
                        <div class="modal fade" id="pop-up-@item.Id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header cstm-pop-up-header">
                                        <button type="button" class="close pop-cross" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title sign-up-title" id="myModalLabel">Delete Confirmation</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>
                                            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
                                            Are you sure you want to proceed?
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                                        <button type="button" data-id="@item.Id" class="btn btn-primary confirmDelete">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>
                </tr>
            }
        }

    </table>
    <script>
        $(".confirmDelete").click(function () {
            var baseUrl = '@Url.Content("~/")';
            var data = { id: $(this).attr("data-id") }
            $.ajax({
                type: "POST",
                url: baseUrl + "Commons/Industry/Delete",
                data: data,
                success: function (data) {
                    if (data == "Success") {
                        $('.close').trigger('click');
                        $("#alert").html(" <b class='alert-success'>Successfully Deleted!Loading New Data...</b>");
                        setTimeout(function () {
                            window.location.replace(baseUrl + "Commons/Industry");//will redirect to your blog page (an ex: blog.html)
                        }, 2000);

                    }
                }
            });
        })
    </script>

</body>
</html>

Mhasb.Wsit.Web.Admin/Views/Industry/Index1.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="row">
    <div class="col-sm-10">
        <div class="box">

            <div class="box-title">
                <h3>
                    <i class="fa fa-table"></i>
                    Industry
                </h3>
                <div style="float:right">
                    @Html.ActionLink("Add New", "Create", null, new { @class = "btn btn-success" })
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "cstm-input" })
                    <button class="btn btn-primary cstm-tbl-srch-btn" id="SearchStringBtn"><i class="fa fa-fw fa-search"></i></button>
                </div>
            </div>

        </div>
        <div class="box-content nopadding">
            <div class="alert alert-success" style="display:none;"></div>
            <div id="LanguageListShow">

            </div>
        </div>
    </div>
</div>




    <script language="javascript" type="text/javascript">
        $(document).ready(function () {

            $.get('@Url.Action("List", "Industry")' + '?page=', function (data) {
                $('#LanguageListShow').html(data);
            }
                );

        });
        $(document).on("click", "#SearchStringBtn", function () {
            var baseUrl = '@Url.Content("~/")';
            var SearchString = $("#SearchString").val();
            var url = baseUrl + "Industry/List?page=''" + "&SearchString=" + SearchString;
            console.log(url);
            $.ajax({
                url: url,
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#LanguageListShow').html(result);
                }
            });
            return false;
        });
    </script>

Mhasb.Wsit.Web.Admin/Views/Industry/List.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Mhasb.Domain.Commons.Industry>



<div id="content">

    <table class="table table-hover table-nomargin table-bordered">
        <tr>
            <th style="text-align: center;">
                Industry Name
                @*@Html.DisplayNameFor(model => model.LanguageName)*@
            </th>
            <th></th>
        </tr>
        @if (!Model.Any())
        {
            <tr><td class="alert-success" colspan="4">There are no Industry</td></tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IndustryName)
                    </td>
                    <td>

                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success" })


                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" })

                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#pop-up-@item.Id">
                            Delete
                        </button>
                        @*<a href="javascript:void(0)"  class="btn btn-primary" data-toggle="modal" data-target="#pop-up-1" data-id="@item.Id">Delete</a>*@
                        <div class="modal fade" id="pop-up-@item.Id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header cstm-pop-up-header">
                                        <button type="button" class="close pop-cross" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title sign-up-title" id="myModalLabel">Delete Confirmation</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>
                                            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
                                            Are you sure you want to proceed?
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                                        <button type="button" data-id="@item.Id" class="btn btn-primary confirmDelete">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>
                </tr>
            }
        }
    </table>

    <div id="contentPager" class="contentPager">
        @Html.PagedListPager(Model, page => Url.Action("List", new { page }))
    </div>
</div>
<script type="text/javascript">
    $(document).on("click", ".contentPager a", function () {
        var currentFilter = $("#SearchString").val();
        var url = $(this).attr("href") + "&currentFilter=" + currentFilter;
        $.ajax({
            url: url,
            type: 'GET',
            cache: false,
            success: function (result) {
                $('#content').html(result);
            }
        });
        return false;
    });

    $(".confirmDelete").click(function () {
        var baseUrl = '@Url.Content("~/")';
        var data = { id: $(this).attr("data-id") }
        $.ajax({
            type: "POST",
            url: baseUrl + "Industry/Delete",
            data: data,
            success: function (data) {
                if (data == "Success") {
                    $('.close').trigger('click');
                    $(".alert").text("Successfully Deleted!Loading New Data...").show("slow");
                    setTimeout(function () {
                        window.location.replace(baseUrl + "Industry");//will redirect to your blog page (an ex: blog.html)
                    }, 2000);

                }
            }
        });
    })
</script>