Mhasb.Wsit.Web/Areas/Inventories/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.IO.Compression;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mhasb.Domain.Inventories;
using Mhasb.Services.Accounts;
using Mhasb.Services.Commons;
using Mhasb.Services.Contact;
using Mhasb.Services.Inventories;
using Mhasb.Services.Loggers;
using Mhasb.Services.OrgSettings;
using Mhasb.Services.Users;

namespace Mhasb.Wsit.Web.Areas.Inventories.Controllers
{
    public class SalesController : Controller
    {
        private IContactInformationService _contactService = new ContactInformationService();
        private readonly IItemService _itemService = new ItemService();
        private readonly ICurrency _currencycService = new CurrencyService();
        private readonly IUserService _uService = new UserService();
        private readonly ICompanyViewLog _companyViewLog = new CompanyViewLogService();
        private readonly ISettingsService _sService = new SettingsService();
        private readonly IChartOfAccountService _coaService = new ChartOfAccountService();
        private readonly ILookupService _luSer = new LookupService();

        //
        // GET: /Inventories/Purchases/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EditBill()
        {
            var user = _uService.GetSingleUserByEmail(HttpContext.User.Identity.Name);
            var accSet = _sService.GetAllByUserId(user.Id);
            ViewBag.User = user.FirstName + "  " + user.LastName;
            if (accSet == null)
            {
                //  return Content("Please add company financial settings ");
                TempData.Add("errMsg", "Please Go To Your Account Seetings to set Default Company");
                return RedirectToAction("Index", "Purchases", new { area = "Inventories" });
            }

            var logObj = _companyViewLog.GetLastViewCompanyByUserId(user.Id);

            var companyId = 0;
            if (logObj.CompanyId != null) companyId = (int)logObj.CompanyId;

            var coalist = _coaService.GetAllChartOfAccountByComIdCostCentre(companyId);
            ViewBag.CoaList = coalist;

            var currencyList = _currencycService.GetAllCurrency();
            ViewBag.CurrencyList = new SelectList(currencyList, "Id", "Name");

            var amountsareenum = Enum.GetValues(typeof(EnumTransactionType))
                                        .Cast<EnumTransactionType>()
                                        .Select(v => new { Id = Convert.ToInt32(v), Name = v.ToString() })
                                        .ToList();
            ViewBag.AmountsareList = new SelectList(amountsareenum, "Id", "Name");

            var lookups = _luSer.GetLookupByType("Tax");//.Select(u => new { u.Id, TValue = u.Value + "(" + u.Quantity + "%)" });
            ViewBag.Lookups = lookups;





            return View();
        }
        
        [HttpPost]
        public ActionResult EditBill(string jsonData )
        {

            return Content("Success");
        }
        public ActionResult PartialAddAccount()
        {
            var user = _uService.GetSingleUserByEmail(HttpContext.User.Identity.Name);
            var logObj = _companyViewLog.GetLastViewCompanyByUserId(user.Id);

            ViewBag.CompanyCompleteFlag = logObj.Companies.CompleteFlag;

            // var AccSet = setService.GetAllByUserId(user.Id);
            int companyId = 0;
            // ReSharper disable once ConditionIsAlwaysTrueOrFalse
            if (logObj != null)
            {
                if (logObj.CompanyId != null) companyId = (int)logObj.CompanyId;
            }
            var atypes = _coaService.GetAllChartOfAccountByCompanyIdForSecondLevel(companyId);


            if (atypes.Count == 0)
            {
                _coaService.AddBaseAccountTypes();
                atypes = _coaService.GetAllChartOfAccountByCompanyId(companyId);
            }
            var lookups = _luSer.GetLookupByType("Tax").Select(u => new { Id = u.Id, Value = u.Value + "(" + u.Quantity + "%)" });
            ViewBag.Lookups = new SelectList(lookups, "Id", "Value");

            ViewBag.ATypes = atypes;
            return PartialView("_AddAccount");
        }

        public ActionResult RepeatTransection()
        {

            return View();
        }
        public JsonResult GetServiceNames(string term)
        {
            var results = _contactService.GetAllContactInformation().Where(s => term == null || s.ContactName.ToLower().Contains(term.ToLower())).Select(x => new { id = x.Id, value = x.ContactName }).Take(5).ToList();

            return Json(results, JsonRequestBehavior.AllowGet);

        }
        public PartialViewResult ItemRow()
        {
            var user = _uService.GetSingleUserByEmail(HttpContext.User.Identity.Name);



            var logObj = _companyViewLog.GetLastViewCompanyByUserId(user.Id);

            var companyId = 0;
            if (logObj.CompanyId != null) companyId = (int)logObj.CompanyId;



            var coalist = _coaService.GetAllChartOfAccountByComIdCostCentre(companyId);
            ViewBag.CoaList = coalist;

            var itemList = _itemService.GetAllItems();
            ViewBag.Items = itemList;
            var lookups = _luSer.GetLookupByType("Tax");//.Select(u => new { u.Id, TValue = u.Value + "(" + u.Quantity + "%)" });
            ViewBag.Lookups = lookups;


            return PartialView();
        }

        public ActionResult GetjsonItem(int Id)
        {
            var user = _uService.GetSingleUserByEmail(HttpContext.User.Identity.Name);
            var logObj = _companyViewLog.GetLastViewCompanyByUserId(user.Id);
            var companyId = 0;
            if (logObj.CompanyId != null) companyId = (int)logObj.CompanyId;
            var itemList = _itemService.GetAllItemsByConmanyId(companyId, Id)
                .Select(u => new
                {
                    u.Id,
                    u.ItemCode,
                    u.ItemName,
                    Description = u.SalesDescription,
                    u.Quantity,
                    UnitPrice =u.SellUnitPrice,
                    AccountId = u.SalesAccount.Id,
                    AccountCode = u.SalesAccount.ACode,
                    AccountName = u.SalesAccount.AName,
                    PtxtValue = u.STaxRate.Key,
                    PtxtQuantity = u.STaxRate.Quantity,
                });

            if (itemList != null)
            {
                return Json(new { itemList });
            }
            else
            {
                return Json(new { success = "False" });
            }

        }
	}
}

Mhasb.Wsit.Web/Areas/Inventories/Views/Sales/Index.cshtml
<div class="container my-dashboard">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="welcome">
                <h3 class="all-head">Error !!</h3>
            </div>
            <div class="row clearfix no-margin">
                <div class="col-md-8 no-padding">
                    @if (TempData["SucMasg"] != null)
                    {
                        <div class="alert alert-success">@TempData["SucMasg"]</div>
                    }
                    @if (TempData["errMsg"] != null)
                    {
                        <div class="alert alert-danger">@TempData["errMsg"]</div>
                    }
                </div>
                <div class="col-md-4">
                    <div class="row clearfix no-margin p-setting-container sidebar-right">
                        <h3>Quick Links</h3>
                        <ul class="nav nav-sidebar">
                            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                            <li><a href="#">Reports</a></li>
                            <li><a href="#">Analytics</a></li>
                            <li><a href="#">Export</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Mhasb.Wsit.Web/Areas/Inventories/Views/Sales/ItemRow.cshtml
<tr class="cstm-table-clr tr-parent">
    
    <td>
        <div class="dropdown form-border">
            <input class="dropdown-toggle itemtXt" type="text"  data-toggle="dropdown" aria-expanded="true">
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a href="javascript:void(0)" role="menuitem" tabindex="-1" class="btn btn-primary" data-toggle="modal" data-target="#itemsModal">+ New Item</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="noneDel">None</a></li>
                @foreach (var item in ViewBag.Items)
                {
                    <li role="presentation"><a role="menuitem" class="itemCliked" tabindex="-1" id="@item.Id" href="javascript:void(0)">@item.ItemCode -  @item.ItemName</a></li>
                }
            </ul>
        </div>
    </td>
    <td><textarea class="cstm-tarea-click description" placeholder="" ></textarea></td>
    <td><textarea class="cstm-tarea-click1 quantity" placeholder="" ></textarea></td>
    <td><textarea class="cstm-tarea-click1 unitPrice" placeholder=""></textarea></td>
    <td>
        <div class="dropdown form-border">
            <input class="dropdown-toggle coAccount" type="text"  data-toggle="dropdown" aria-expanded="true">
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
               
                <li role="presentation"><a href="#accountModal" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">+ Add new account...</a></li>
                @foreach (var item in ViewBag.CoaList)
                {
                    <li role="presentation"><a role="menuitem" class="itemSelected" tabindex="-1" href="javascript:void(0)">@item.ACode - @item.AName</a></li>
                }
            </ul>
           
        </div>
    </td>
    <td>
        <div class="dropdown form-border">
            <input class="dropdown-toggle taxPer" type="text"  data-toggle="dropdown" aria-expanded="true">
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#" data-toggle="modal" class="btn btn-primary" data-target="#taxModal">+ Add new tax rate...</a></li>
                @foreach (var item in ViewBag.Lookups)
                {
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">@item.Value (@item.Quantity%) </a></li>
                }
            </ul>
        </div>
    </td>
    <td  class="ammount"></td>
    <td  class="ammounttax" style="display:none;"></td>
    <td class="crossx2"><a href="javascript:void(0);" class="presentation RemoveRow">X</a></td>
</tr>

@*@{ Html.RenderAction("PartialAddAccount"); }*@




<script type="text/javascript">
    $(document).ready(function () {
        $('.noneDel').unbind("click").bind("click", function () {
            var par = $(this).parent('li').parent('ul').parent().parent().parent();
            par.find('.itemtXt').val();
            par.find('.description').val();
            par.find('.quantity').val();
            par.find('.unitPrice').val();
            par.find('.coAccount').val();
            par.find('.taxPer').val();
            par.find('.ammount').text();
            par.find('.ammounttax').text();
            $('#sub-total').text();
            $('#calTax').text();
            $('#total').text();
        });

        $(".RemoveRow").unbind("click").bind("click", function () {
            var th=$(this).parent('.crossx2').parent('.tr-parent');
            var amount = parseFloat(th.find('.ammount').text()).toFixed(2);
            var ammounttax = parseFloat(th.find('.ammounttax').text()).toFixed(2);
            var sub_total = parseFloat($("#sub-total").text()).toFixed(2);
            var Tax_total = parseFloat($("#calTax").text()).toFixed(2);
            var total = parseFloat($("#total").text()).toFixed(2);
            if (sub_total >= amount) {
                sub_total = (sub_total - amount).toFixed(2);
                $("#sub-total").text(sub_total);
            }
            if (Tax_total >= ammounttax) {
                Tax_total = parseFloat(Tax_total - ammounttax).toFixed(2);
                $("#calTax").text(Tax_total);
            }
            
            if (total >= sub_total) {
                
                var t = parseFloat((amount * (ammounttax / 100))).toFixed(2);
                
                var amountDitect = parseFloat(amount) + parseFloat(t);
                
                total =parseFloat( total - amountDitect.toFixed(2)).toFixed(2);
                $("#total").text(total);
            }
           
            $(this).closest('tr').remove();
        });
        $('.itemCliked').click(function () {
            var Id = $(this).attr("id");
            var par = $(this).parent('li').parent('ul').parent().parent().parent();
            
            console.log(par);
            var presubtotal = $('#sub-total').text();
            var prevcalTax = $('#calTax').text();
            var prevtotal = $('#total').text();
            
            $.ajax({
                url: "@Url.Action("GetjsonItem", "Sales", new { area = "Inventories" })",
                type: "POST",
                data: { Id: Id },
                success: function (data) {
                    var json = $.parseJSON(JSON.stringify(data));
                    var data = json.itemList[0];
                    console.log(data);
                    if (json.success == "False") {
                        console.log("Error");
                    } else {
                        var ammount = data.Quantity * data.UnitPrice;
                        var subTotal = 0.00;
                        var TotalTax = 0.00;
                        var allTotal = 0.00;
                        par.find('.itemtXt').val(data.ItemName);
                        par.find('.description').val(data.Description);
                        par.find('.quantity').val(data.Quantity);
                        par.find('.unitPrice').val(data.UnitPrice);
                        par.find('.coAccount').val(data.AccountCode + " - " + data.AccountName);
                        par.find('.taxPer').val(data.PtxtValue + "(" + data.PtxtQuantity + "%)");
                        par.find('.ammount').text(ammount );
                        par.find('.ammounttax').text(parseFloat(data.PtxtQuantity).toFixed(2));
                        presubtotal = parseFloat(presubtotal) + ammount;
                        $('.tr-parent').each(function () {
                            var eachAmmount = parseFloat($(this).find('.ammount').text()).toFixed(2);
                            subTotal = parseFloat(subTotal) + parseFloat(eachAmmount);
                            $('#sub-total').text(subTotal.toFixed(2));

                            var eachAmmounttax = parseFloat($(this).find('.ammounttax').text()).toFixed(2);
                            TotalTax = parseFloat(TotalTax) + parseFloat(eachAmmounttax);
                            $('#calTax').text(TotalTax.toFixed(2));
                            eachAmmount = parseFloat(eachAmmount) + parseFloat(eachAmmount * (eachAmmounttax / 100));
                            console.log(eachAmmount);
                            allTotal = parseFloat(allTotal) + parseFloat(eachAmmount);
                            $('#total').text(allTotal.toFixed(2));


                        });
                       // //$('#sub-total').text(parseFloat(presubtotal).toFixed(2));
                       // //prevcalTax = parseFloat(prevcalTax) + data.PtxtQuantity;
                       //// $('#calTax').text(parseFloat(prevcalTax).toFixed(2));
                       // var total;
                       // if (data.PtxtQuantity >=0) {
                       //     total = ammount + (ammount * (data.PtxtQuantity / 100)) + parseFloat(prevtotal);
                       //     }else{
                       //     total = ammount + parseFloat(prevtotal);
                       //     }
                        
                       // $('#total').text(parseFloat(total).toFixed(2));
                    }
                },
                error: function () {
                    console.log("Error");
                }
            });
        });
    });
</script>

Mhasb.Wsit.Web/Areas/Inventories/Views/Sales/_AddAccount.cshtml
@model Mhasb.Domain.Accounts.ChartOfAccount
@{Layout = null;}


<!-- Large modal -->
@*<a class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Add New Account</a>*@

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="accountModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content clearfix">

            <div class="modal-header cstm-pop-up-header">
                <button type="button" class="close pop-cross" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title sign-up-title" id="myModalLabel">Add New Account</h4>
            </div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="col-md-6">

                    <div class="row cstm-frm-row">
                        <div class="col-md-4">
                            <label>Account Type:</label>
                        </div>
                        <div class="col-md-8">
                            <select class="cstm-input" id="Aid" name="atype" required="required">
                                <option value="">--Select Account Type--</option>
                                @foreach (var items in ViewBag.Atypes)
                                {
                                    if (items.Level == 1)
                                    {
                                        <optgroup label=@items.AName></optgroup>
                                    }
                                    else
                                    {
                                        <option value="@items.Id">@items.AName</option>
                                    }
                                }
                            </select>
                            @*@Html.DropDownList("atype", (SelectList)ViewBag.ATypes, "--Select Account Type--", htmlAttributes: new { @class = "cstm-input", id = "Aid", required = "required" })*@
                        </div>
                    </div>
                    <div class="row cstm-frm-row">
                        <div class="col-md-4">
                            <label>Account Name</label>
                        </div>
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.AName, new { @class = "cstm-input" })
                        </div>
                    </div>
                    <div class="row cstm-frm-row">
                        <div class="col-md-4">
                            <label>Account Code</label>
                        </div>
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.ACode, new { @class = "cstm-input", id = "code" })
                        </div>
                    </div>
                    <div class="row cstm-frm-row">
                        <div class="col-md-4">
                            <label>Account Description</label>
                        </div>
                        <div class="col-md-8">
                            @Html.TextAreaFor(m => m.Description, new { @class = "cstm-tarea", placeholder = "Type a text here" })
                        </div>
                    </div>
                    <div class="row cstm-frm-row">
                        <div class="col-md-4">
                            <label>Account Tax</label>
                        </div>
                        <div class="col-md-8">

                            @Html.DropDownList("TaxId", (SelectList)ViewBag.Lookups, "--Select Tax --", htmlAttributes: new { @class = "cstm-input", id = "Aid", required = "required" })
                        </div>
                    </div>
                    @*<div class="row cstm-frm-row">
                            <div class="col-md-4">
                                <label>Account Nature</label>
                            </div>
                            <div class="col-md-8">
                                <select class="cstm-input">
                                    <option value="">--Select Account Nature--</option>
                                    <option value="">Debit</option>
                                    <option value="">Credit </option>

                                </select>
                            </div>
                        </div>*@


                    <div class="row cstm-frm-row">

                        <div class="col-md-12">
                            <label>
                                @Html.CheckBoxFor(m => m.ShowInDashboard)
                                Show on Dashboard Watchlist
                            </label>
                        </div>
                    </div>
                    <div class="row cstm-frm-row">

                        <div class="col-md-12">
                            <label>
                                @Html.CheckBoxFor(m => m.ShowInExpenseClaims) Show in Expense Claims
                            </label>
                        </div>
                    </div>
                    <div class="row cstm-frm-row">

                        <div class="col-md-12">
                            <label>
                                @Html.CheckBoxFor(m => m.IsCostCenter)This Account Is a Cost Center
                            </label>
                        </div>
                    </div>
                    @Html.HiddenFor(m => m.Level, new { id = "level" })
                    <div class="row cstm-frm-row">
                        <div class="col-md-12">
                            <div class="btn-group" role="group" aria-label="...">
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-success">Save</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="col-md-6">
                    <img src="~/img/chartofaccount.png" />
                </div>
            }



        </div>
    </div>
</div>




<script>
    $("#Aid").change(function () {
        var baseUrl = '@Url.Content("~/")';
        var url = $("#getCode").attr("data-url");
        var id = $(this).val();
        var data = { id: id }
        $.ajax({
            type: "POST",
            url: baseUrl + "Accounts/ChartOfAccounts/GetCode",
            data: data,
            datatype: "html",
            success: function (data) {
                $("#code").val(data.code);
                $("#code").attr('readonly', 'readonly');
                $("#level").val(data.lavel);

            }
        });
    })
</script>