Mhasb.Wsit.Web/Areas/UserManagement/Controllers/ActionListController.cs
using Mhasb.Domain.Users;
using Mhasb.Services.Users;
using Mhasb.Wsit.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace Mhasb.Wsit.Web.Areas.UserManagement.Controllers
{
    public class ActionListController : BaseController
    {
        private IActionListService actionListService = new ActionListService();

        public ActionResult Index()
        {
           // var model = actionListService.GetAllActionList();
            return View();
        }
        
        
        //method for paging and search option
        public ActionResult List(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            List<ActionList> Al = actionListService.GetAllActionList();
            if (!String.IsNullOrEmpty(searchString))
            {
                Al = Al.Where(s => s.ActionName.Contains(searchString)
                                   || s.ControllerName.Contains(searchString)
                                   || s.ModuleName.Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return PartialView(Al.ToPagedList(pageNumber, pageSize));

        }


        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ActionList actionList)
        {
            actionListService.AddActionList(actionList);
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = actionListService.GetSingleActionList(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]

        public ActionResult Edit(ActionList actionList)
        {
            actionListService.UpdateActionList(actionList);
            //return View();
            return RedirectToAction("Index");
        }

    }

}

Mhasb.Wsit.Web/Areas/UserManagement/Views/ActionList/Create.cshtml
@model Mhasb.Domain.Users.ActionList

@{
    ViewBag.Title = "CreateActionList";
}

<div class="container my-dashboard">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="welcome">
                <h4><a href="#">Create Action</a></h4>
         <div class="alert-danger">Actions are auto genarated</div>
            </div>
            @using (Html.BeginForm(new { @class = "organization-details-form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="form-group ">
                    @Html.LabelFor(model=>model.ModuleName)
                    @Html.TextBoxFor(model => model.ModuleName, htmlAttributes: new { @class = "form-control", placeholder = "Module Name", id = "role_name", validate = "RequiredField", style = "border:1px solid #b6b6b6;" })
                    @Html.ValidationMessageFor(model => model.ModuleName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ControllerName)
                    @Html.TextBoxFor(model => model.ControllerName, htmlAttributes: new { @class = "form-control", placeholder = "Controller Name", id = "remarks", validate = "RequiredField", style = "border:1px solid #b6b6b6;" })
                    @Html.ValidationMessageFor(model => model.ControllerName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ActionName)
                    @Html.TextBoxFor(model => model.ActionName, htmlAttributes: new { @class = "form-control", placeholder = "Action Name", id = "remarks", validate = "RequiredField", style = "border:1px solid #b6b6b6;" })
                    @Html.ValidationMessageFor(model => model.ActionName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.NameToShow)
                    @Html.TextBoxFor(model => model.NameToShow, htmlAttributes: new { @class = "form-control", placeholder = "Name To Show", id = "remarks", validate = "RequiredField", style = "border:1px solid #b6b6b6;" })
                    @Html.ValidationMessageFor(model => model.NameToShow)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.OrderNo)
                    @Html.TextBoxFor(model => model.OrderNo, htmlAttributes: new { @class = "form-control", placeholder = "Order No", id = "remarks", validate = "RequiredField", style = "border:1px solid #b6b6b6;" })
                    @Html.ValidationMessageFor(model => model.OrderNo)
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <button class="btn btn-default btn-success" type="submit" style="margin-bottom:10px;">Save</button>
                    </div>
                </div>
            }

        </div>
    </div>
    </div>
    @*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

Mhasb.Wsit.Web/Areas/UserManagement/Views/ActionList/Edit.cshtml
@model Mhasb.Domain.Users.ActionList

@{
    ViewBag.Title = "EditActionList";
}

<div class="container my-dashboard">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="welcome">
                <h4><a href="#">Edit Action</a></h4>

            </div>
            @using (Html.BeginForm(new { @class = "organization-details-form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <div class="form-group ">
                    @Html.LabelFor(model => model.ModuleName)
                    @Html.TextBoxFor(model => model.ModuleName, htmlAttributes: new { @class = "form-control", placeholder = "Module Name", id = "role_name", validate = "RequiredField", style = "border:1px solid #b6b6b6;", @readonly="readonly" })
                    @Html.ValidationMessageFor(model => model.ModuleName)
                </div>
                <div class="form-group">
                    <label>Submodule Name</label>
                    @Html.TextBoxFor(model => model.ControllerName, htmlAttributes: new { @class = "form-control", placeholder = "Controller Name", id = "remarks", validate = "RequiredField", style = "border:1px solid #b6b6b6;",@readonly="readonly" })
                    @Html.ValidationMessageFor(model => model.ControllerName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ActionName)
                    @Html.TextBoxFor(model => model.ActionName, htmlAttributes: new { @class = "form-control", placeholder = "Action Name", id = "remarks", validate = "RequiredField", style = "border:1px solid #b6b6b6;", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.ActionName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.NameToShow)
                    @Html.TextBoxFor(model => model.NameToShow, htmlAttributes: new { @class = "form-control", placeholder = "Name To Show", id = "remarks", validate = "RequiredField", style = "border:1px solid #b6b6b6;", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.NameToShow)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.OrderNo)
                    @Html.TextBoxFor(model => model.OrderNo, htmlAttributes: new { @class = "form-control", placeholder = "Order No", id = "remarks", validate = "RequiredField", style = "border:1px solid #b6b6b6;", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.OrderNo)
                </div>
                <div class="row">

                    <div class="col-md-12">
                        <button class="btn btn-default btn-success" type="submit" style="margin-bottom:10px;">Save</button>
                       @Html.ActionLink("Back To List", "Index")
                    </div>
                </div>
            }

        </div>
    </div>
    @Scripts.Render("~/bundles/jqueryval")
   

Mhasb.Wsit.Web/Areas/UserManagement/Views/ActionList/Index.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Country";
}
<style>
    .link {
        margin-bottom: 10px;
        color: #fff;
    }
</style>

<div class="container">
    <div class="col-md-12">
        <h2>Index</h2>

        <div class="btn btn-success" style="margin-bottom:10px;color:#fff;">
            @Html.ActionLink("Create New", "Create", new { @class = "link" })
            &nbsp;<i class="fa fa-plus-circle">
            </i>
        </div>
        <p>
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="button" id="SearchStringBtn" value="Search" />
        </p>
        <div id="ActionListListShow">

        </div>
    </div>
</div>



@section scripts
{
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $.get('@Url.Action("List", "ActionList", new { Area = "UserManagement" })' + '?page=', function (data) {
                $('#ActionListListShow').html(data);
            }
            );
       
        });

        $(document).on("click", "#SearchStringBtn", function () {
            var baseUrl = '@Url.Content("~/")';
            var SearchString = $("#SearchString").val();
            var url = baseUrl + "UserManagement/ActionList/List?page=''" + "&SearchString=" + SearchString;
            $.ajax({
                url: url,
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#content').html(result);
                }
            });
            return false;
        });
    </script>
}

Mhasb.Wsit.Web/Areas/UserManagement/Views/ActionList/Index_old.cshtml
@model IEnumerable<Mhasb.Domain.Users.ActionList>

@{
    ViewBag.Title = "Action List";
}
<style>
    .link {
        margin-bottom: 10px;
        color: #fff;
    }
</style>

<div class="container">
    <div class="col-md-12">
    <h2>Index</h2>

    <div class="btn btn-success" style="margin-bottom:10px;color:#fff;">
        @Html.ActionLink("Create New", "Create", new { @class = "link" })
        &nbsp;<i class="fa fa-plus-circle">
        </i>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>
               Module Name
            </th>
            <th>
             Sub Module Name
            </th>
            <th>
                Action Name
            </th>
            <th>
                Name To Show
            </th>
            <th>
                Order No
            </th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ModuleName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ControllerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActionName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameToShow)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderNo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) 
                    @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                </td>
            </tr>
        }

    </table>
</div>
</div>

Mhasb.Wsit.Web/Areas/UserManagement/Views/ActionList/List.cshtml
@model PagedList.IPagedList<Mhasb.Domain.Users.ActionList>
@using PagedList.Mvc;
<div id="content">

    <table class="table table-bordered">
        <tr>
            <th>Module Name </th>
            <th>Sub Module Name</th>
            <th>Action Name</th>
            <th>Name To Show</th>
            <th>Order No</th>
            <th>Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ModuleName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ControllerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ActionName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameToShow)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderNo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                </td>
            </tr>
        }

    </table>

    <div id="contentPager" class="contentPager">
        @Html.PagedListPager(Model, page => Url.Action("List", new { page }))
    </div>
</div>
<script type="text/javascript">
    $(document).on("click", ".contentPager a", function () {
        var currentFilter = $("#SearchString").val();

        var url = $(this).attr("href") + "&currentFilter=" + currentFilter;
        $.ajax({
            url: url,
            type: 'GET',
            cache: false,
            success: function (result) {
                $('#content').html(result);
            }
        });
        return false;
    });

    $(document).ready(function () {

    });



</script>