Mhasb.Wsit.Web/Areas/Commons/Controllers/CountryController.cs
using Mhasb.Domain.Commons;
using Mhasb.Services.Commons;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;


namespace Mhasb.Wsit.Web.Areas.Commons.Controllers
{
    public class CountryController : Controller
    {
        private ICountryService coService = new CountryService();
        //
        // GET: /Commons/Country/
        public ActionResult Index()
        {
            //var model=coService.GetAllCountries();
            //return View(model);
            return View("Index1");
        }

        public ActionResult List(string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;  
            }
            ViewBag.CurrentFilter = searchString;
            List<Country> Country = coService.GetAllCountries();
            if (!String.IsNullOrEmpty(searchString))
            {
                Country = Country.Where(s => s.CountryName.Contains(searchString)).ToList();
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return PartialView(Country.ToPagedList(pageNumber, pageSize));

        }

        //
        // GET: /Commons/Country/Details/5
        public ActionResult Details(int id)
        {
            var model = coService.GetSingleCountry(id);
            return View(model);
        }

        //
        // GET: /Commons/Country/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Commons/Country/Create
        [HttpPost]
        public ActionResult Create(Country country)
        {
            try
            {
                coService.CreateCountry(country);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Commons/Country/Edit/5
        public ActionResult Edit(int id)
        {
            var model = coService.GetSingleCountry(id);
            return View(model);
        }

        //
        // POST: /Commons/Country/Edit/5
        [HttpPost]
        public ActionResult Edit(Country country)
        {
            try
            {
                coService.UpdateCountry(country);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        public String DeleteConfirmed(int id)
        {
            try
            {
                coService.DeleteCountry(id);
                return "Success";
                // return RedirectToAction("Index");
            }
            catch
            {
                return "Failed";
            }
        }
    }
}

Mhasb.Wsit.Web/Areas/Commons/Views/Country/Create.cshtml
@model Mhasb.Domain.Commons.Country
<div class="container my-dashboard">
    <div class="row clearfix">
        <div class="col-md-6">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="row cstm-frm-row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.CountryName)
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.CountryName, new { @class = "cstm-input" })
                @Html.ValidationMessageFor(model => model.CountryName)
            </div>
        </div>
        <div class="row cstm-frm-row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.CountryCode)
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.CountryCode, new { @class = "cstm-input" })
                @Html.ValidationMessageFor(model => model.CountryCode)
            </div>
        </div>
        <div class="row cstm-frm-row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.ShortName)
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.ShortName, new { @class = "cstm-input" })
                @Html.ValidationMessageFor(model => model.ShortName)
            </div>
        </div>

        <div class="row cstm-frm-row">
            <div class="col-md-12">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
            }
        @Scripts.Render("~/bundles/jqueryval")
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
    </div>
</div>

Mhasb.Wsit.Web/Areas/Commons/Views/Country/Edit.cshtml
@model Mhasb.Domain.Commons.Country
<div class="container my-dashboard">
    <div class="row clearfix">
        <div class="col-md-6">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Country</h4>
                    <hr />
                    @Html.ValidationSummary(true)

                    <div class="row cstm-frm-row">
                        <div class="col-md-4">
                            @Html.LabelFor(model => model.CountryName)
                        </div>
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.CountryName, new { @class = "cstm-input" })
                            @Html.ValidationMessageFor(model => model.CountryName)
                        </div>
                    </div>
                    <div class="row cstm-frm-row">
                        <div class="col-md-4">
                            @Html.LabelFor(model => model.CountryCode)
                        </div>
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.CountryCode, new { @class = "cstm-input" })
                            @Html.ValidationMessageFor(model => model.CountryCode)
                        </div>
                    </div>
                    <div class="row cstm-frm-row">
                        <div class="col-md-4">
                            @Html.LabelFor(model => model.ShortName)
                        </div>
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.ShortName, new { @class = "cstm-input" })
                            @Html.ValidationMessageFor(model => model.ShortName)
                        </div>
                    </div>

                    <div class="row cstm-frm-row">
                        <div class="col-md-12">
                            <input type="submit" value="Update" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
            @Scripts.Render("~/bundles/jqueryval")
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>

Mhasb.Wsit.Web/Areas/Commons/Views/Country/Index1.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="container my-dashboard">
    <div class="row">
        <div class="col-md-10">

            <div class="col-md-2">

                @Html.ActionLink("Create New", "Create", "Country", new { area = "Commons" }, new { @class = "btn btn-success" })
            </div>
            <div class="col-md-6 pull-right no-padding">

                <p>
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "cstm-input", style = "width:88%" })
                    <button class="btn btn-info cstm-tbl-srch-btn" id="SearchStringBtn"><i class="fa fa-fw fa-search"></i></button>
                    @*  <input type="button" id="SearchStringBtn" class="btn btn-info" value="Search" /><i class="fa fa-fw fa-search"></i>*@
                </p>
            </div>


            @*@Html.Action("List")*@
        </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-10">
                    <div class="alert alert-success" style="display:none;"></div>
                    <div id="CountryListShow">

                    </div>
                </div>
            </div>
        </div>
        @*<div class="row clearfix">
            <div class="col-md-6">

                <p class="btn btn-success link">
                    @Html.ActionLink("Create New", "Create", "Country", new { area = "Commons" }, new { @class = "link" })
                </p>
                <p>
                    Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                    <input type="button" id="SearchStringBtn" value="Search" />
                </p>


                <div id="CountryListShow">

                </div>*@
                @*@Html.Action("List")*@
            @*</div>
        </div>*@
    </div>

@section scripts
{
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $.get('@Url.Action("List", "Country", new { Area = "Commons" })' + '?page=', function (data) {
                $('#CountryListShow').html(data);
            }
            );
            //$(document).on("click", "#contentPager a[href]", function () {
            //    $.ajax({
            //        url: $(this).attr("href"),
            //        type: 'GET',
            //        cache: false,
            //        success: function (result) {
            //            $('#content').html(result);
            //        }
            //    });
            //    return false;
            //});
        });

        $(document).on("click", "#SearchStringBtn", function () {
            var baseUrl = '@Url.Content("~/")';
            var SearchString = $("#SearchString").val();
            var url = baseUrl + "Commons/Country/List?page=''" + "&SearchString=" + SearchString;
            $.ajax({
                url: url,
                type: 'GET',
                cache: false,

                success: function (result) {
                    $('#content').html(result);
                }
            });
            return false;
        });
    </script>
}

@*<script language="javascript" type="text/javascript">
        $(document).ready(function () {
            alert("Russel");
            $.get('@Url.Action("List", "Student", new { Area = "" })' + '?page=', function (data) {

                $('#StudentListShow').html(data);
            }
            );
            //$(document).on("click", "#contentPager a[href]", function () {
            //    $.ajax({
            //        url: $(this).attr("href"),
            //        type: 'GET',
            //        cache: false,
            //        success: function (result) {
            //            $('#content').html(result);
            //        }
            //    });
            //    return false;
            //});
        });
    </script>*@

Mhasb.Wsit.Web/Areas/Commons/Views/Country/List.cshtml
@model PagedList.IPagedList<Mhasb.Domain.Commons.Country>
@using PagedList.Mvc;
<div id="content">
    @*<table class="table table-bordered" style="text-align: center;">
            <tbody>
                <tr>
                    <th style="text-align: center;">
                        RoleName
                    </th>
                    <th style="text-align: center;">
                        Remarks
                    </th>
                </tr>

                <tr>
                    <td>
                        Helo
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="">
                            Delete
                        </button>
                        <a data-role="button" class="btn btn-info" data-toggle="modal" data-target="">
                            Details
                        </a>
                        <a data-role="button" class="btn btn-success" data-toggle="modal" data-target="">
                            Edit
                        </a>
                    </td>
                </tr>

            </tbody>
        </table>*@
    <table class="table table-bordered" style="text-align: center;">
        <tr>
            <th style="text-align: center;">
                Country Name
            </th>
            <th style="text-align: center;">
                CountryCode
            </th>
            <th style="text-align: center;">
                ShortName
            </th>
            <th></th>
        </tr>

        @if (!Model.Any())
        {
            <tr><td class="alert-success" colspan="4">There are no Country</td></tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CountryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CountryCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShortName)
                    </td>
                    <td>
                          @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success" }) 
                        
                            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
                      
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#pop-up-@item.Id">
                            Delete
                        </button>
                        @*<a href="javascript:void(0)"  class="btn btn-primary" data-toggle="modal" data-target="#pop-up-1" data-id="@item.Id">Delete</a>*@
                        <div class="modal fade" id="pop-up-@item.Id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header cstm-pop-up-header">
                                        <button type="button" class="close pop-cross" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title sign-up-title" id="myModalLabel">Delete Confirmation</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>
                                            <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
                                            Are you sure you want to proceed?
                                        </p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                                        <button type="button" data-id="@item.Id" class="btn btn-primary confirmDelete">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        }
    </table>

    <div id="contentPager" class="contentPager">
        @Html.PagedListPager(Model, page => Url.Action("List", new { page }))
    </div>
</div>
<script type="text/javascript">
    $(document).on("click", ".contentPager a", function () {
        var currentFilter = $("#SearchString").val();
       
        var url = $(this).attr("href") + "&currentFilter=" + currentFilter;
        $.ajax({
            url: url,
            type: 'GET',
            cache: false,
            //beforeSend: function () {
            //    //$(placeholder).addClass('loading');
            //   // $('#loader-wrapper').show();
            //    $('#loader-wrapper').css('display','block');
            //},
            success: function (result) {
                $('#content').html(result);

            },
            //complete: function () {
            //    //$(placeholder).removeClass('loading');
            //    //$('#loader-wrapper').hide();
            //    $('#loader-wrapper').css('display', 'none');
            //}
        });
        return false;
    });

    $(document).ready(function () {
        @*$("#SearchStringBtn").trigger('click', function () {
            var baseUrl = '@Url.Content("~/")';
            var SearchString = $("#SearchString").val();
            var url = baseUrl + "Student/List?page=''" + "&SearchString=" + SearchString;
            $.ajax({
                url: url,
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#content').html(result);
                }
            });
            return false;
        });*@
    });

    $(document).on("click", "#SearchStringBtn", function () {
        var baseUrl = '@Url.Content("~/")';
        var SearchString = $("#SearchString").val();
        var url = baseUrl + "Student/List?page=''" + "&SearchString=" + currentFilter;
        $.ajax({
            url: url,
            type: 'GET',
            cache: false,
            success: function (result) {
                $('#content').html(result);
            }
        });
        return false;
    });

</script>

<script>
    $(".confirmDelete").click(function () {
        var baseUrl = '@Url.Content("~/")';
        var data = { id: $(this).attr("data-id") }
        $.ajax({
            type: "POST",
            url: baseUrl + "Commons/Country/Delete",
            data: data,
            success: function (data) {
                if (data == "Success") {
                    $('.close').trigger('click');
                    $(".alert").text("Successfully Deleted!Loading New Data...").show("slow");
                    setTimeout(function () {
                        window.location.replace(baseUrl + "Commons/Country");//will redirect to your blog page (an ex: blog.html)
                    }, 2000);

                }
            }
        });
    })
</script>